### ISSUE TITLE
Strange ArticulationParameters value (rotating a turret)

### ISSUE THREAD

**Issue by rattlesnake2028** [AF-GRILL/DISPluginForUnreal#16]
Hi there, I have a turret rotating from left to right slowly and sending on DIS

In wireshark I can capture this ArticulationParameters[0] / ParameterValue :
0 => 0.78 (turning right) and then 0 => -0.78 (turning left) (which are fine values)

But using the DIS plugin I can get this : 
0 => 0.000765 (turning right) and then 0 => -0.000765 (turning left) (which are strange values)

So I tought I would have to multiply by 1000 the ParameterValue... but even with this the rotating turret is animated in a jerky rather than linear fashion.

Do you have any ideas why the values are so much different ?

**Comment by jhuggins0214** [comment]
Are you performing both sending and receiving of the DIS packets from the DIS plugin? From running small tests on our end, the articulation parameters parameter value is received as expected when performing both sending and receiving with the DIS plugin.

**Comment by jhuggins0214** [comment]
Closing as there haven't been any updates for a few months.

Feel free to reopen if the issue persists.

**Comment by rattlesnake2028** [comment]
Hello and sorry for the late answer.

In case it can help someone, I had to convert the received value from double to float in order to get the proper value I was looking for (in radiant).

Here is the patch :

Edit the file `GRILLDISForUnreal\Source\DISRuntime\Public\PDUs\EntityInfoFamily\GRILL_EntityStatePDU.h`

```cpp
		//Articulation Parameters
		for (int i = 0; i < EntityStatePDUIn.getNumberOfArticulationParameters(); i++)
		{
			DIS::ArticulationParameter tempArtParam = EntityStatePDUIn.getArticulationParameters()[i];
			FArticulationParameters newArtParam;
			newArtParam.ParameterTypeDesignator = tempArtParam.getParameterTypeDesignator();
			newArtParam.ChangeIndicator = tempArtParam.getChangeIndicator();
			newArtParam.PartAttachedTo = tempArtParam.getPartAttachedTo();
			newArtParam.ParameterType = tempArtParam.getParameterType();

			if (newArtParam.ParameterTypeDesignator == 0)
			{
				//newArtParam.ParameterValue = tempArtParam.getParameterValue(); //Old code wich returns wrong double value

				double initialParamValue = tempArtParam.getParameterValue(); // New line added
				newArtParam.ParameterValue = ConvertUpperDoubleToFloat(initialParamValue); // New line added
			}
			else
			{
				newArtParam.AttachedPartType = tempArtParam.getParameterValue();
			}

			ArticulationParameters.Add(newArtParam);
		}
	}

	// New function added
	// Definition of the function that converts the upper 32 bits of a double value into a float
	float ConvertUpperDoubleToFloat(double dval) {
		uint64_t dvalAsInt;
		memcpy(&dvalAsInt, &dval, sizeof(double)); // Copies the binary representation of the double value into an integer variable

		uint32_t upper32Bits = dvalAsInt >> 32; // Extract the upper 32 bits

		float result;
		memcpy(&result, &upper32Bits, sizeof(uint32_t)); // Convert upper 32 bits to float

		return result; // Returns the resulting float value
	}
```
