### ISSUE TITLE
"On received Detonation PDU" Event does not trigger

### ISSUE THREAD

**Issue by rattlesnake2028** [AF-GRILL/DISPluginForUnreal#17]
Hello there,

I receive a DIS scenario where an entity A is shooting an entity B.

The event "On received Fire PDU" is working as expected when the entity A fires.

However the "On received Detonation PDU" Event does not trigger on entity B when its damaged or dead.

Tried on both unreal 4 et 5.3

Is it working on your side ?

**Comment by jhuggins0214** [comment]
We're receiving detonation events on our side. Verify when you're sending out the detonation PDU that the Exercise ID matches that of your sim and that the Munition ID matches the entity ID of the fired munition.

For damaging targets, the received detonation PDU will have to be manually handled to determine the entity that was hit by the munition.

**Comment by jhuggins0214** [comment]
Closing as there haven't been any updates for a few months.

Feel free to reopen if the issue persists.

**Comment by rattlesnake2028** [comment]
Hello jhuggins0214,
The exercice ID is correct but indeed If I look the fire event inside wireshark I can see that the munition ID is empty :
![image](https://github.com/AF-GRILL/DISPluginForUnreal/assets/43271521/eb251c18-f222-4091-88cc-2dd3d11d782a)

I guess, the Munition ID should be filled in order for the 'Detonation PDU' to be triggered ?

**Comment by jhuggins0214** [comment]
You'll still have to generate a Detonation PDU for when your munition detonates, the Fire PDU won't automatically trigger it for you.

We currently use the Munition ID to process Detonation PDUs when one is received. If it doesn't align with an existing Entity ID, it gets ignored. 

This is an oversight on our end though and is something we'll push an update for as there are times when a munition is not represented by an entity, but will still send want to send out a Detonation PDU at the end of its travel.

**Comment by rattlesnake2028** [comment]
Thank you very much for this explanation it helps me a lot.
Is there any ETA for this update ? Just in order for me to find the proper workflow in the mean time

**Comment by jhuggins0214** [comment]
We should have it pushed up by the end of this work week. If not, it'll be end of next week at the latest.

**Comment by jhuggins0214** [comment]
An update has been pushed allowing for Detonation PDUs with no specified entity set as their Munition ID. Since they don't tie to an entity, they get handled by the DIS Game Manager which has a new event on it that can be bound to.

Note: We also updated the OpenDIS Third Party files with these updates. You may need to regenerate your Unreal Engine Visual Studio solution in order for it to build properly. You also made need to delete your Binaries and Intermediate folder prior to doing this to make sure Unreal generates it properly.

Let us know if you have any issues with the update.

**Comment by ghost** [comment]
Thank you very much, I made a simple test and it seems to work !
