### ISSUE TITLE
When PDU receives data, UE5.3 will crash

### ISSUE THREAD

**Issue by ethanzh1** [AF-GRILL/DISPluginForUnreal#18]
Hello,

After upgrading to UE5.3.2, UE will crash when receiving data. (Everything was perfect in 5.0.3)

![20240318144335](https://github.com/AF-GRILL/DISPluginForUnreal/assets/6285722/4d6c8ae3-c21b-44dc-bd5d-10d865f0381d)

The key code is in this line. If I remove this line of code, it seems that the data can be received normally, but I guess this seems wrong, and I don't know what impact this will have.

![20240318144354](https://github.com/AF-GRILL/DISPluginForUnreal/assets/6285722/a6d9dce5-0f08-4950-86b1-e7472df3ca8e)

Is there any way to fix this crash? Thanks.

**Comment by jhuggins0214** [comment]
You could put a try-catch statement in that switch case to see if the exception that gets thrown has any more info in it.

That's a function from the [NPS OpenDIS libraries](https://github.com/open-dis/open-dis-cpp) that we use to help convert DIS network packets to a friendly readable format. These files are located in our plugin inside of the "Source/ThirdParty/include/_dis version_" folders.

Fire PDUs seem to work fine in 5.3 on our end with the test DIS scenarios we use. The main thing that comes to mind for us is that it could be a malformed Fire PDU packet, but that shouldn't be the case if it all worked fine for you in 5.0.

**Comment by ethanzh1** [comment]
On my side, the crash occurs 100% of the time while listening to data, and every time it crashes, I'm only running one project with the DIS plugin.
When I run the package for shipping, it crashes with a “Fatal Error".

By the way, when it crashes (on PIE), the code jumps here:

![5e611552479af69fdae56329ab8fc9c](https://github.com/AF-GRILL/DISPluginForUnreal/assets/6285722/333f99ff-5e93-4a37-bf6b-11afa46fe8bc)

![5ed9b39e9059aaf8f409677106c7e5a](https://github.com/AF-GRILL/DISPluginForUnreal/assets/6285722/c6b1f207-88a6-4a1a-9125-2c4a6f5f2bfd)

**Comment by jhuggins0214** [comment]
The length of your Fire PDUs that you are receiving seems to be incorrect. Fire PDUs should be 96 bytes in length, but the "InData" variable is only 84 bytes. This would cause the "invalid vector subscript" error that you're getting since the DIS standard is trying to read outside of the vector bounds due to it expecting a specific length for the Fire PDU DIS packets.

We'll add in a check for this as that's something we should be verifying on our end before trying to unmarshall it.

**Comment by jhuggins0214** [comment]
Closing as there haven't been any updates for a few months.

Feel free to reopen if the issue persists.
