### ISSUE TITLE
How to build for Linux

### ISSUE THREAD

**Issue by Neurowerk** [AF-GRILL/DISPluginForUnreal#5]
Hi,
Thanks for DIS realization for Unreal Engine as plugin. 
But how to build it for Unreal Engine 5 at Linux platform?

**Comment by jhuggins0214** [comment]
Sorry for the delayed response.

The DIS plugin should build fine for Linux, but we haven't tried as our lab primarily uses Windows. Feel free to let us know if there are any issues with building it for Linux that relate back to our plugin.

As for building an Unreal Engine project for Linux, Epic Games should have documentation on their website that steps you through how to do that.
